print("Hello, I'm SpIdY. I am a chatbot")
print("I like animals and I love to talk about food")
name=input("What's your name?:")
print("Hello",name,"Nice to meet you")
year =input("I am not very good at dates. what is the year?: ")
print("Yes, I think that is correct. Thanks! ")
myage = input("Can you guess my age? - enter a number: ")
print("Yes you are right. i am", myage)
myage = int(myage)
nyears = 100 - myage
print("I will be 100 in",nyears,"years")
print("That will be the year", int(year) + nyears)
print("I love chocolate and I also like trying out new kinds of food")
food= input("How about you? What is your favorite food?: ")
print("I like", food, "too.")
question= "How often do you eat " +food+"?:"
howoften = input(question)
print("Interesting. I wonder if that is good for your health")
animal = input("my favorite animal is a giraffe. what is yours?: ")
print(animal,"! I do not like them. ")
print("I wonder if ", animal,"likes to eat", food)
feeling = input("How are you feeling today?: ")
print("Why are you feeling", feeling, "now? ")
reason = input("please tell me: ")
print("I understand. Thanks for sharing")
print("It has been a long day")
print("I am too tired to talk, we can chat again later. ")
print("Goodbye", name, "I liked chatting with you")