num=[0,2,5,9,5,12]
print('original list: ',num)
num.append(20)
print('appended num.20:',num)
num.remove(20)
print('removed num.20',num)
num.insert(1,15)
print('inserted num.15 on index 1:',num)
num.pop()
print('removed last item:',num)
print('index of 5 is',num.index(5))
print('check 9 num is available in list:', 9 in num)
print('how many times 5 num is?',num.count(5))
num.sort()
print('after sorting ',num)
num.reverse()
print('descending list is after sorting', num)
num2=num.copy()
num.append(55)
print('copy method',num2)
num.clear()
print('clearing the list',num)